[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer clear-cache --working-dir=Painel || true",
  "composer dump-autoload --optimize --working-dir=Painel || true",
  "composer install --no-dev --optimize-autoloader --no-cache --working-dir=Painel || true"
]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"
