[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "cd Painel && composer clear-cache",
  "cd Painel && composer dump-autoload --optimize",
  "cd Painel && composer install --no-dev --optimize-autoloader --no-cache"
]

[phases.build]
cmds = []

[start]
cmd = "cd Painel && php artisan serve --host=0.0.0.0 --port=$PORT"
